### ISSUE TITLE
monotonicity guarantees

### ISSUE THREAD

**Issue by ailisp** [tailhook/cpu-time#4]
Found by @matklad:
monotonicity isn't guaranteed, especially when the process is migrated between CPUs.
https://docs.rs/cpu-time/1.0.0/src/cpu_time/clock_gettime.rs.html#38
```
unsafe { clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &mut time) }
...
    /// Returns the amount of CPU time used from the previous timestamp.
    pub fn duration_since(&self, timestamp: Self) -> Duration {
        self.0 - timestamp.0
    }
```

From https://linux.die.net/man/3/clock_gettime: 
>    The CLOCK_PROCESS_CPUTIME_ID and CLOCK_THREAD_CPUTIME_ID clocks are realized on many platforms using timers from the CPUs (TSC on i386, AR.ITC on Itanium). These registers may differ between CPUs and as a consequence these clocks may return bogus results if a process is migrated to another CPU.

So seems like this can panic?
https://doc.rust-lang.org/stable/src/core/time.rs.html#875-881

**Comment by tailhook** [comment]
The idea of CPU time as I understand is that: CPU register is read every time process switches from userspace to kernel space (because at this point process may start sleeping), and all of that is summed up into some per-process storage. So when process is moved by a scheduler to a different processor it starts a new time slice on that processor anyway.

Also thing that you cite is mentioned under "historical notes" on recent systems (not sure why `linux.die.net` is outdated):
![note](https://user-images.githubusercontent.com/321799/106883943-58504200-66e9-11eb-9b3f-43d887eb4c39.jpg)
And there is another paragraph below:
> Since  glibc  2.4,  the  wrapper functions for the system calls described in
>       this page avoid the abovementioned problems by employing the  kernel  imple‐
>       mentation  of  CLOCK_PROCESS_CPUTIME_ID and CLOCK_THREAD_CPUTIME_ID, on sys‐
>       tems that provide such an implementation (i.e., Linux 2.6.12 and later).

(note versions of glibc and linux kernel mentioned are about 15 years old)

**Comment by tailhook** [comment]
Another note that there are `try_now` and `try_elapsed` if you want to avoid panics at all costs.

**Comment by ailisp** [comment]
@tailhook You're right, not an issue on a modern OS. Thank you!
